# Generated by Django 4.0.3 on 2023-06-04 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.client'),
        ),
    ]
