# Generated by Django 4.0.3 on 2023-06-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_date_added_alter_article_last_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='stock',
            new_name='quantite',
        ),
    ]
