# Generated by Django 3.1.3 on 2023-06-27 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.article'),
        ),
    ]
