# Generated by Django 3.1.3 on 2023-06-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20230627_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.article'),
        ),
    ]
