# Generated by Django 3.1.3 on 2023-06-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20230627_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
