# Generated by Django 5.0.7 on 2024-09-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_stock_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('laname', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('passwrd', models.CharField(default='', max_length=50)),
                ('isAccepted', models.BooleanField()),
            ],
        ),
    ]
